# Generated by Django 4.0.1 on 2022-01-07 01:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=100)),
                ('certificate_issued', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('long_desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tech_used', models.CharField(max_length=20)),
                ('proj_url', models.URLField(blank=True)),
                ('blog_link', models.URLField(blank=True)),
                ('proj_img', models.ImageField(default='proj_default_img.png', upload_to='projects_images')),
            ],
            options={
                'ordering': ('-proj_title',),
            },
        ),
        migrations.CreateModel(
            name='ReadingListening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(blank=True, max_length=200)),
                ('AudioName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
