# Generated by Django 4.0.1 on 2022-01-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutme_rename_audioname_readinglistening_audioname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
