# Generated by Django 4.0.1 on 2022-01-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='top_project',
            field=models.BooleanField(default=False),
        ),
    ]
